name: .NET
on: push

jobs:
  job:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.100-rc.2.20479.15
      - name: Build
        run: dotnet build OptivumParser --configuration Release
      - name: Build Api
        run: dotnet build OptivumParser.Api --configuration Release
      - name: Test
        run: dotnet test OptivumParser.Tests
