name: .NET
on:
  push:
    branches:
      - master

jobs:
  job:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.201
      - name: Build
        run: dotnet build OptivumParser --configuration Release
      - name: Build Api
        run: dotnet build OptivumParser.Api --configuration Release
      - name: Test
        run: dotnet test OptivumParser.Tests
      - name: Publish NuGet package
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: OptivumParser/OptivumParser.csproj
          PACKAGE_NAME: OptivumParser
          NUGET_KEY: ${{secrets.NUGET_KEY}}
